Repository huggingface/optimum-habana, pull requests merged in 2023-11, with the labels that each got.

#524 fixing update method - avoid copy idx to cpu which splitting the graph
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test

#521 Enable llama attention softmax in bf16
  examples/language-modeling/run_lora_clm.py
  optimum/habana/transformers/models/llama/modeling_llama.py
  optimum/habana/transformers/trainer.py
  tests/baselines/llama_7b.json
Labels: run-test, synapse 1.13

#529 Add load_meta_device option to reduce host RAM
  examples/language-modeling/run_lora_clm.py
Labels: synapse 1.13

#513 Add infra to enable/disable dynamic shapes feature through gaudi_config
  optimum/habana/transformers/gaudi_configuration.py
  optimum/habana/transformers/trainer.py
  tests/test_trainer.py
Labels: run-test

#532 Improve llama performance and reduce memory consumption by updating sin/cos cache when inferring more than max position embeddings (4096)
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test

#523 refactor run generation
  examples/text-generation/run_generation.py
  examples/text-generation/utils.py
  optimum/habana/checkpoint_utils.py
Labels: run-test, synapse 1.13

#534 Add hash_with_views arg for Falcon inference perf
  Makefile
  examples/text-generation/README.md
  examples/text-generation/run_generation.py
  examples/text-generation/utils.py
  optimum/habana/utils.py
  tests/test_text_generation_example.py
Labels: run-test, synapse 1.13

#540 Fix split by whitespaces not a single space
  optimum/habana/utils.py
Labels: run-test

#536 Update PEFT model example
  examples/text-generation/README.md
Labels: synapse 1.13

#553 Fix setting of reuse cache
  examples/text-generation/run_generation.py
Labels: run-test

#542 Add llamav2 fp8 inference
  examples/text-generation/README.md
  examples/text-generation/run_generation.py
  examples/text-generation/utils.py
  optimum/habana/transformers/generation/configuration_utils.py
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: synapse 1.13

#487 Add Deepspeed zero3 configuration to run bloom-7b on Gaudi1
  examples/language-modeling/README.md
  tests/baselines/bloom_7b1.json
  tests/configs/deepspeed_zero_3_gaudi1.json
  tests/test_examples.py
  tests/utils.py
Labels: synapse 1.13

#349 Remove HMP from optimum-habana
  docs/source/package_reference/gaudi_config.mdx
  docs/source/usage_guides/accelerate_training.mdx
  examples/audio-classification/README.md
  examples/audio-classification/run_audio_classification.py
  examples/contrastive-image-text/README.md
  examples/contrastive-image-text/run_bridgetower.py
  examples/contrastive-image-text/run_clip.py
  examples/image-classification/README.md
  examples/image-classification/run_image_classification.py
  examples/language-modeling/README.md
  examples/language-modeling/run_clm.py
  examples/language-modeling/run_mlm.py
  examples/question-answering/README.md
  examples/question-answering/run_qa.py
  examples/question-answering/run_seq2seq_qa.py
  examples/speech-recognition/README.md
  examples/speech-recognition/run_speech_recognition_ctc.py
  examples/summarization/README.md
  examples/summarization/run_summarization.py
  examples/text-classification/README.md
  examples/text-classification/run_glue.py
  examples/translation/README.md
  examples/translation/run_translation.py
  optimum/habana/diffusers/pipelines/pipeline_utils.py
  optimum/habana/transformers/gaudi_configuration.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/albert/modeling_albert.py
  optimum/habana/transformers/models/gpt2/modeling_gpt2.py
  optimum/habana/transformers/models/modeling_all_models.py
  optimum/habana/transformers/models/opt/modeling_opt.py
  optimum/habana/transformers/trainer.py
  tests/configs/gaudi_config_trainer_test.json
  tests/test_diffusers.py
  tests/test_gaudi_configuration.py
Labels: run-test, synapse 1.13

#541 adding lm eval script
  examples/text-generation/README.md
  examples/text-generation/requirements_lm_eval.txt
  examples/text-generation/run_lm_eval.py
Labels: synapse 1.13

#485 Tgi Sharded feature
  text-generation-inference/Dockerfile
  text-generation-inference/README.md
  text-generation-inference/launcher/src/main.rs
  text-generation-inference/server/pyproject.toml
  text-generation-inference/server/requirements.txt
  text-generation-inference/server/text_generation_server/cli.py
  text-generation-inference/server/text_generation_server/models/causal_lm.py
  text-generation-inference/server/text_generation_server/models/model.py
  text-generation-inference/server/text_generation_server/server.py
  text-generation-inference/server/text_generation_server/tgi_service.py
Labels: synapse 1.13

#537 Enable Falcon 180B
  examples/language-modeling/README.md
  examples/language-modeling/ds_falcon_180b_z3.json
  examples/language-modeling/run_lora_clm.py
Labels: run-test, synapse 1.13
