Repository huggingface/optimum-habana, pull requests merged in 2024-08, with the labels that each got.

#1086 Change the device_id for FSDP plugin
  optimum/habana/accelerate/accelerator.py
  optimum/habana/accelerate/utils/dataclasses.py
Labels: synapse 1.17_dependency

#1160 Set KV Cache update as static method
  optimum/habana/transformers/models/falcon/modeling_falcon.py
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test, synapse1.17

#1158 refine use cache for mpt model
  optimum/habana/transformers/models/mpt/modeling_mpt.py
Labels: run-test, synapse1.17

#1157 To fix CPU tensor issue
  optimum/habana/transformers/generation/utils.py
Labels: run-test, synapse1.17

#1099 Adds a helm chart, dockerfile, and instructions for running examples using a Kubernetes cluster
  examples/kubernetes/Chart.yaml
  examples/kubernetes/Dockerfile
  examples/kubernetes/README.md
  examples/kubernetes/README.md.gotmpl
  examples/kubernetes/ci/multi-card-glue-values.yaml
  examples/kubernetes/ci/multi-card-lora-clm-values.yaml
  examples/kubernetes/ci/single-card-glue-values.yaml
  examples/kubernetes/ci/single-card-lora-clm-values.yaml
  examples/kubernetes/docker-compose.yaml
  examples/kubernetes/requirements.txt
  examples/kubernetes/templates/dataaccess.yaml
  examples/kubernetes/templates/gaudi-job.yaml
  examples/kubernetes/templates/pvc.yaml
  examples/kubernetes/templates/secret.yaml
  examples/kubernetes/values.yaml
Labels: run-test, synapse1.17

#1094 GPT-J support reuse_cache
  examples/text-generation/run_lm_eval.py
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/gptj/__init__.py
  optimum/habana/transformers/models/gptj/modeling_gptj.py
  tests/test_text_generation_example.py
Labels: run-test, synapse1.17

#1133 deciLM support
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/decilm/__init__.py
  optimum/habana/transformers/models/decilm/configuration_decilm.py
  optimum/habana/transformers/models/decilm/modeling_decilm.py
  tests/test_text_generation_example.py
Labels: run-test, synapse1.17

#915 add example of multitask_prompt/poly tuning
  examples/language-modeling/README.md
  examples/language-modeling/peft_poly_seq2seq_with_generate.py
  examples/language-modeling/run_multitask_prompt_tuning.py
  optimum/habana/peft/__init__.py
  optimum/habana/peft/layer.py
  tests/baselines/t5_small.json
  tests/test_examples.py
Labels: run-test, synapse1.17

#1146 fix data-type mismatch for mlperf_inference accuracy test
  optimum/habana/transformers/generation/utils.py
Labels: run-test, synapse1.17

#1153 Sd3
  examples/stable-diffusion/text_to_image_generation.py
  optimum/habana/diffusers/__init__.py
  optimum/habana/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py
  setup.py
  tests/test_diffusers.py
Labels: run-test, synapse1.17

#943 Add support for contrastive search
  examples/text-generation/README.md
  examples/text-generation/run_generation.py
  examples/text-generation/utils.py
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/gpt2/__init__.py
  optimum/habana/transformers/models/gpt2/modeling_gpt2.py
  tests/test_text_generation_example.py
  tests/transformers/tests/generation/test_utils.py
  tests/transformers/tests/models/gptj/test_modeling_gptj.py
Labels: run-test, synapse1.17

#1159 use fast softmax only on prefill
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test, synapse1.17

#1202 Fix max_position_embedding init for tf4.43 upgrade
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test, synapse1.17

#1131 fix spawn MP context, limit cpu and download data
  examples/text-generation/requirements_lm_eval.txt
  examples/text-generation/run_lm_eval.py
Labels: run-test, synapse1.17

#1205 Fix max_position_embedding error for Mixtral
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test

#1149 Starcoder2 : KVCache and flash attention (FusedSDPA) enablement
  examples/text-generation/run_lm_eval.py
  examples/text-generation/utils.py
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/starcoder2/__init__.py
  optimum/habana/transformers/models/starcoder2/modeling_starcoder2.py
  optimum/habana/transformers/trainer.py
Labels: run-test, synapse1.17

#1223 sarkar/Fix VIT, add wav2vec comment
  optimum/habana/transformers/models/wav2vec2/modeling_wav2vec2.py
  tests/transformers/tests/test_modeling_common.py
Labels: synapse1.17

#1228 work around llama torch.compile performance issue
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: synapse1.17

#1226 Fix bert/roberta contrastive search tests
  tests/transformers/tests/generation/test_utils.py
Labels: synapse1.17

#1165 Support loading hugging face checkpoint
  examples/text-generation/README.md
  examples/text-generation/run_generation.py
  examples/text-generation/utils.py
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: synapse 1.17_dependency

#1234 gptj: fix missing token_idx
  optimum/habana/transformers/models/gptj/modeling_gptj.py
Labels: run-test

#1247 fix(nltk): fixed the version to working one
  examples/summarization/requirements.txt
Labels: synapse1.17

#1221 Updating to avoid hardcoding tests in CI framework
  tests/ci/sentence_transformers.sh
Labels: synapse1.17

#1251 Fix FSDP graph error due to Tranformer 4.43 update
  examples/language-modeling/fsdp_config.json
  examples/question-answering/fsdp_config.json
  optimum/habana/accelerate/accelerator.py
  optimum/habana/transformers/training_args.py
Labels: synapse1.17

#1250 Ig/sw_196666 sd
  examples/stable-diffusion/README.md
Labels: synapse1.17

#1260 Gpt bigcode fused sdpa
  examples/text-generation/README.md
  examples/text-generation/run_generation.py
  examples/text-generation/utils.py
  optimum/habana/transformers/models/mixtral/modeling_mixtral.py
Labels: synapse1.17

#1101 Enable FusedSDPA for Mpt
  optimum/habana/transformers/models/mpt/modeling_mpt.py
Labels: run-test, review wip

#1288 Add missing condtion check in tensor creation in greedy search
  optimum/habana/transformers/generation/utils.py
Labels: OH_1.13.1_Candidates

#1281 Fix BERT FSDP test
  optimum/habana/accelerate/utils/__init__.py
  optimum/habana/accelerate/utils/other.py
  optimum/habana/transformers/modeling_utils.py
Labels: OH_1.13.1_Candidates

#1285 Update FusedSDPA calling method as Gaudi documentation
  optimum/habana/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py
Labels: run-test
