Repository huggingface/optimum-habana, pull requests merged in 2024-10, with the labels that each got.

#1387 Enhance transformers test suite in Optimum-habana-4.43.4 Auto pr 07654de
  tests/transformers/tests/models/llama/test_modeling_llama.py
  tests/transformers/tests/models/mistral/test_modeling_mistral.py
  tests/transformers/tests/models/mixtral/test_modeling_mixtral.py
  tests/transformers/tests/models/vit/test_modeling_vit.py
  tests/transformers/tests/models/wav2vec2/test_modeling_wav2vec2.py
Labels: run-test

#1386 Enhance transformers test suite in Optimum-habana-4.43.4 (auto PR 8926a4b)
  tests/transformers/tests/models/bert/test_modeling_bert.py
  tests/transformers/tests/models/bridgetower/test_modeling_bridgetower.py
  tests/transformers/tests/models/falcon/test_modeling_falcon.py
  tests/transformers/tests/models/gpt2/test_modeling_gpt2.py
Labels: run-test

#1355 add README.md for Sentence transformer examples with HPU device
  examples/sentence-transformers-training/README.md
Labels: run-test

#1368 Change Falcon/GPT-Neox rotary embedding function to use seq_len for
  optimum/habana/transformers/modeling_rope_utils.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/falcon/modeling_falcon.py
  optimum/habana/transformers/models/gpt_neox/__init__.py
  optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py
  optimum/habana/transformers/models/persimmon/__init__.py
  optimum/habana/transformers/models/persimmon/modeling_persimmon.py
  optimum/habana/transformers/models/phi/modeling_phi.py
  optimum/habana/transformers/models/qwen2/modeling_qwen2.py
  optimum/habana/transformers/models/stablelm/__init__.py
  optimum/habana/transformers/models/stablelm/modeling_stablelm.py
  optimum/habana/transformers/models/starcoder2/modeling_starcoder2.py
Labels: run-test

#1381 Enhance Optimum-habana as per transformers-4.43.4
  tests/transformers/tests/models/gpt_neox/test_modeling_gpt_neox.py
  tests/transformers/tests/models/gptj/test_modeling_gptj.py
  tests/transformers/tests/models/swin/test_modeling_swin.py
Labels: run-test

#1316 Added Qwen2-MoE model, optimizing its performance on Gaudi
  README.md
  docs/source/index.mdx
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/qwen2_moe/__init__.py
  optimum/habana/transformers/models/qwen2_moe/modeling_qwen2_moe.py
  tests/test_text_generation_example.py
Labels: run-test

#1194 refine bucket_internal for mpt
  optimum/habana/transformers/models/mpt/modeling_mpt.py
Labels: run-test

#1037 Porting Stable Video Diffusion ControNet to HPU
  examples/stable-diffusion/README.md
  examples/stable-diffusion/image_to_video_generation.py
  optimum/habana/diffusers/__init__.py
  optimum/habana/diffusers/models/__init__.py
  optimum/habana/diffusers/models/controlnet_sdv.py
  optimum/habana/diffusers/models/unet_spatio_temporal_condition_controlnet.py
  optimum/habana/diffusers/pipelines/controlnet/pipeline_stable_video_diffusion_controlnet.py
  tests/test_diffusers.py
Labels: run-test

#1130 sasarkar/qwen finetuning bucketing
  examples/trl/sft.py
  optimum/habana/trl/trainer/sft_trainer.py
  tests/baselines/Qwen2_72B.json
  tests/test_examples.py
  tests/utils.py
Labels: run-test

#1394 Truncate the cached max seq len
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test

#1397 Fix gpt-neox training accuracy issue.
  optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py
Labels: run-test

#1219 Simplify HQT config files
  examples/text-generation/quantization_config/act_maxabs_pow2_weights_pcs_opt_pow2_quant.json
  examples/text-generation/quantization_config/maxabs_measure.json
  examples/text-generation/quantization_config/maxabs_measure_include_outputs.json
  examples/text-generation/quantization_config/maxabs_quant.json
  examples/text-generation/quantization_config/maxabs_quant_phi.json
  examples/text-generation/quantization_config/unit_scale_quant.json
Labels: synapse 1.18 dependency

#1322 unify_measurements.py script support to unify PCQ 70B 8x
  examples/text-generation/quantization_tools/unify_measurements.py
Labels: synapse 1.18 dependency

#1346 Add misc. training args
  examples/summarization/run_summarization.py
  optimum/habana/accelerate/accelerator.py
  optimum/habana/transformers/trainer.py
  optimum/habana/transformers/training_args.py
Labels: synapse 1.18 dependency

#1377 Add quantization config for low bs case
  examples/text-generation/quantization_config/maxabs_quant_scalar_scales.json
Labels: synapse 1.18 dependency

#1257 Remove HQT from OHF
  examples/image-to-text/README.md
  examples/image-to-text/run_pipeline.py
  examples/text-generation/utils.py
Labels: synapse 1.18 dependency

#1364 Load INC GPTQ checkpoint & rename params
  Makefile
  examples/text-generation/README.md
  examples/text-generation/run_generation.py
  examples/text-generation/utils.py
  tests/test_text_generation_example.py
Labels: synapse 1.18 dependency

#1388 Enable FusedSDPA fp8 in Llama FT
  examples/language-modeling/run_lora_clm.py
  optimum/habana/accelerate/utils/transformer_engine.py
  optimum/habana/transformers/models/llama/configuration_llama.py
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: synapse 1.18 dependency

#1183 sarkar/Valid sequence length for sdpa
  examples/text-generation/run_generation.py
  examples/text-generation/utils.py
  optimum/habana/transformers/generation/configuration_utils.py
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: synapse 1.18 dependency

#1406 change the order for test_diffusers
  Makefile
Labels: run-test

#1410 Multiple fixes (dynamo graph break, qwen-moe, multicard)
  optimum/habana/transformers/models/llama/modeling_llama.py
  optimum/habana/transformers/models/qwen2_moe/modeling_qwen2_moe.py
Labels: run-test

#1402 fix llama model text generation error
  optimum/habana/transformers/generation/utils.py
Labels: run-test

#1358 Fix GPT_neox incorrect output with batch query
  optimum/habana/transformers/generation/utils.py
Labels: run-test

#1424 Update ci sentence_transformer.sh
  tests/ci/sentence_transformers.sh
Labels: synapse1.18

#1422 Update language-modeling README.md, add trust_remote_code for flan-t5-xl
  examples/language-modeling/README.md
  examples/text-generation/README.md
Labels: synapse1.18

#1425 Update unify_measurements.py support info
  examples/text-generation/README.md
Labels: synapse1.18

#1427 add peft generation example
  examples/text-generation/README.md
Labels: synapse1.18

#1418 Upgrade to SynapseAI 1.18.0
  .github/workflows/fast_tests.yml
  .github/workflows/slow_tests.yml
  .github/workflows/slow_tests_gaudi2.yml
  Makefile
  README.md
  docs/Dockerfile
  docs/source/installation.mdx
  docs/source/usage_guides/deepspeed.mdx
  examples/audio-classification/README.md
  examples/gaudi_spawn.py
  examples/kubernetes/Dockerfile
  examples/kubernetes/README.md
  examples/kubernetes/README.md.gotmpl
  examples/kubernetes/docker-compose.yaml
  examples/multi-node-training/EFA/Dockerfile
  examples/multi-node-training/GaudiNIC/Dockerfile
  examples/speech-recognition/README.md
  examples/text-generation/README.md
  examples/text-generation/text-generation-pipeline/README.md
  notebooks/AI_HW_Summit_2022.ipynb
  optimum/habana/accelerate/accelerator.py
  optimum/habana/accelerate/state.py
  optimum/habana/utils.py
Labels: synapse1.18

#1431 Added missing allocate_kv_cache() call in CausalLM class
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/models/gemma/modeling_gemma.py
Labels: synapse1.18

#1434 GPT2 torch.compile fix
  examples/text-generation/utils.py
Labels: synapse1.18

#1436 fix merge error and update text-to-speech readme
  examples/text-generation/README.md
  examples/text-generation/run_generation.py
  examples/text-to-speech/README.md
Labels: synapse1.18

#1437 Fix OOM error for code llama
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: synapse1.18

#1432 Fix scoped linear all-reduce for starcoder model
  optimum/habana/transformers/models/modeling_all_models.py
  optimum/habana/transformers/models/starcoder2/modeling_starcoder2.py
Labels: run-test

#1445 Added gemma specific fp8 quantization file
  examples/text-generation/README.md
  examples/text-generation/quantization_config/maxabs_quant_gemma.json
Labels: synapse1.18

#1455 Enable DeepSpeed for image-to-text example
  examples/image-to-text/README.md
  examples/image-to-text/run_pipeline.py
  optimum/habana/transformers/models/clip/modeling_clip.py
Labels: run-test

#1457 Fixes 'Tokenizer does not have padding token' introduced by #1444 for Llama3.1
  examples/language-modeling/run_lora_clm.py
Labels: run-test

#1447 fix bug when loading 4bit checkpoint quantized in INC
  examples/text-generation/utils.py
Labels: run-test

#1433 fix facebook/hf-seamless-m4t-medium crash
  examples/text-to-speech/README.md
  optimum/habana/transformers/generation/utils.py
Labels: run-test
