Repository huggingface/optimum-habana, pull requests merged in 2024-12, with the labels that each got.

#1506 Migrate OH T5-large training to torch.compile
  examples/summarization/README.md
Labels: run-test

#1475 enable DeepSeek-V2
  README.md
  docs/source/index.mdx
  examples/text-generation/run_generation.py
  examples/text-generation/utils.py
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/deepseek_v2/__init__.py
  optimum/habana/transformers/models/deepseek_v2/configuration_deepseek_v2.py
  optimum/habana/transformers/models/deepseek_v2/modeling_deepseek_v2.py
  optimum/habana/transformers/models/deepseek_v2/tokenization_deepseek_v2.py
  tests/test_text_generation_example.py
Labels: run-test

#1519 Add support for optimized SDXL pipeline
  examples/stable-diffusion/README.md
  examples/stable-diffusion/quantization/measure/fp8_hooks_maxabs.json
  examples/stable-diffusion/quantization/measure/fp8_hooks_maxabs.npz
  examples/stable-diffusion/quantization/measure_config.json
  examples/stable-diffusion/quantization/quant_config.json
  examples/stable-diffusion/text_to_image_generation.py
  optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
  optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_mlperf.py
Labels: run-test

#1496 Fixes in unify_measurements
  examples/text-generation/README.md
  examples/text-generation/quantization_tools/unify_measurements.py
Labels: synapse_1.19_dependency

#1514 Add option to use bf16 in PT sdp (#5)
  examples/stable-diffusion/text_to_image_generation.py
  optimum/habana/diffusers/pipelines/pipeline_utils.py
  optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
  optimum/habana/transformers/training_args.py
Labels: run-test

#1508 [wav2vec2] Remove tensor.item and dynamic slicing operations in the loop that cause graph break
  optimum/habana/transformers/models/wav2vec2/modeling_wav2vec2.py
Labels: run-test

#1473 update lm_eval version
  examples/text-generation/README.md
  examples/text-generation/requirements_lm_eval.txt
  examples/text-generation/run_lm_eval.py
Labels: run-test

#1459 Enable pyTorch-IMage-Models (TIMM) with HPUs
  examples/pytorch-image-models/README.md
  examples/pytorch-image-models/inference.py
  examples/pytorch-image-models/requirements.txt
  examples/pytorch-image-models/train_hpu_graph.py
  examples/pytorch-image-models/train_hpu_lazy.py
  tests/test_timm.py
Labels: run-test

#1501 Adding support for Context Parallelism using Deepseed's DistributedAt…
  optimum/habana/accelerate/accelerator.py
  optimum/habana/accelerate/data_loader.py
  optimum/habana/accelerate/state.py
  optimum/habana/distributed/contextparallel.py
  optimum/habana/parallel_state.py
  optimum/habana/transformers/models/llama/modeling_llama.py
  optimum/habana/transformers/trainer.py
  optimum/habana/transformers/training_args.py
  tests/baselines/llama_7b.json
  tests/test_examples.py
Labels: run-test, synapse_1.19_dependency

#1511 Add DynamicMoE support for Mixtral
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/mixtral/__init__.py
  optimum/habana/transformers/models/mixtral/modeling_mixtral.py
Labels: run-test

#1548 Fix for llava models not generating text with test failures in 1.19
  examples/image-to-text/README.md
  tests/test_image_to_text_example.py
Labels: run-test

#1148 Refactor KV cache, Rope , reduce common code
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/clip/modeling_clip.py
  optimum/habana/transformers/models/falcon/modeling_falcon.py
  optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py
  optimum/habana/transformers/models/llama/modeling_llama.py
  optimum/habana/transformers/models/mistral/modeling_mistral.py
  optimum/habana/transformers/models/mixtral/modeling_mixtral.py
  optimum/habana/transformers/models/modeling_all_models.py
  optimum/habana/transformers/models/phi/modeling_phi.py
  optimum/habana/transformers/models/qwen2/modeling_qwen2.py
  optimum/habana/transformers/models/starcoder2/modeling_starcoder2.py
Labels: run-test

#1557 Apply --sdp_on_bf16 to image-to-text examples
  examples/image-to-text/README.md
  examples/image-to-text/run_pipeline.py
  tests/test_image_to_text_example.py
Labels: run-test

#1556 Fix accuracy regression in Gemma
  optimum/habana/transformers/models/gemma/modeling_gemma.py
  tests/test_text_generation_example.py
Labels: run-test

#1563 Run albert-xxlarge-v1 CI as torch.compile mode
  tests/baselines/albert_xxlarge_v1.json
  tests/test_examples.py
Labels: run-test

#1566 Update README commands for the models to use --sdp_on_bf16
  examples/contrastive-image-text/README.md
  examples/question-answering/README.md
  examples/speech-recognition/README.md
  examples/text-classification/README.md
Labels: run-test

#1567 Minicpm patch
  examples/text-generation/utils.py
Labels: run-test

#1561 Updated gemma_2b_it CI
  tests/baselines/gemma_2b_it.json
  tests/test_examples.py
Labels: run-test

#1564 Fixed Adalora Test for OH 1.15
  tests/test_examples.py
Labels: run-test

#1568 Fixed LORACP Test for OH 1.15
  tests/baselines/llama_7b.json
Labels: run-test

#1565 fusedsdpa for stable diffusion xl
  optimum/habana/diffusers/models/unet_2d_condition.py
  optimum/habana/diffusers/pipelines/pipeline_utils.py
  optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
  optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
  tests/test_diffusers.py
  tests/test_examples.py
Labels: run-test

#1559 add sdp_on_bf16 to tests,text-gen
  examples/text-generation/run_generation.py
  tests/test_encoder_decoder.py
  tests/test_examples.py
  tests/test_fsdp_examples.py
  tests/test_image_to_text_example.py
  tests/test_text_generation_example.py
Labels: run-test

#1569 fix mllama test
  optimum/habana/transformers/generation/utils.py
Labels: run-test

#1558 fix lazy_mode assignment
  optimum/habana/transformers/trainer.py
Labels: run-test

#1574 fix diffusers import
  optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
Labels: run-test

#1575 Update README commands for more models to use --sdp_on_bf16
  examples/image-to-text/README.md
  examples/question-answering/README.md
  examples/speech-recognition/README.md
  examples/text-classification/README.md
  examples/text-generation/README.md
  tests/test_text_generation_example.py
Labels: run-test

#1478 Add chatglm
  README.md
  docs/source/index.mdx
  examples/language-modeling/README.md
  examples/language-modeling/run_clm.py
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/chatglm/__init__.py
  optimum/habana/transformers/models/chatglm/configuration_chatglm.py
  optimum/habana/transformers/models/chatglm/modeling_chatglm.py
  optimum/habana/transformers/models/chatglm/tokenization_chatglm.py
  optimum/habana/transformers/trainer.py
  tests/baselines/chatglm3_6b.json
  tests/test_examples.py
  tests/test_text_generation_example.py
  tests/utils.py
Labels: synapse1.20

#1578 Revert "add check_neural_compressor_min_version for 4 bit behavior"
  examples/text-generation/utils.py
  optimum/habana/utils.py
Labels: run-test

#1585 add sdp_on_bf16 argument to CI for run_image2text_lora_finetune and a…
  tests/baselines/Llama_3_2_11B_Vision_Instruct.json
  tests/test_examples.py
Labels: run-test

#1584 Remove unnecessary neural compressor fix for 1.19 release
  examples/text-generation/utils.py
Labels: run-test

#1576 Fixed spelling
  optimum/habana/transformers/models/detr/modeling_detr.py
  optimum/habana/transformers/trainer.py
  optimum/habana/transformers/training_args.py
Labels: run-test

#1588 adjust bert and roberta targets
  tests/baselines/bert_large_uncased_whole_word_masking.json
  tests/baselines/roberta_large.json
  tests/test_text_generation_example.py
Labels: run-test

#1589 update text-gen readme for autogptq
  examples/text-generation/README.md
Labels: run-test

#1555 Update README to Include Information on Performance Degradation and Mitigation Options
  README.md
  examples/audio-classification/README.md
  examples/image-classification/README.md
  examples/sentence-transformers-training/paraphrases/training_paraphrases.py
  examples/stable-diffusion/training/README.md
Labels: run-test

#1587 readme update for llama-405B
  examples/text-generation/README.md
Labels: run-test

#1590 Add WA flag for falcon-180b to resolve text-gen critical reset error during tests
  tests/test_text_generation_example.py
Labels: run-test

#1592 add sdp_on_bf16 option to diffusers and image/audio classicifation tests
  tests/test_diffusers.py
  tests/test_examples.py
Labels: run-test

#1595 Update README.md
  examples/pytorch-image-models/README.md
Labels: run-test

#1598 Limit position embeddings in inference
  examples/text-generation/utils.py
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test, synapse_1.19_dependency

#1608 Replace the UNET custom attention processors
  tests/test_diffusers.py
Labels: run-test

#1609 Check rope_scaling attr
  examples/text-generation/utils.py
Labels: run-test

#1621 Fix run_generation test commands for TRL out usage example
  examples/trl/README.md
Labels: run-test

#1643 Fix `save_lora_weights` in `pipeline_utils.py`
  optimum/habana/diffusers/pipelines/pipeline_utils.py
Labels: run-test

#1635 refactor mixtral moe block.
  examples/trl/README.md
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/mixtral/__init__.py
  optimum/habana/transformers/models/mixtral/modeling_mixtral.py
Labels: run-test

#1646 speech-recognition: downgrade datasets version
  examples/speech-recognition/requirements.txt
Labels: run-test

#1664 Add reuse_cache for llama3-405b measurement
  examples/multi-node-training/GaudiNIC/Dockerfile
  examples/text-generation/README.md
Labels: run-test

#1665 Update EFA dockerfile to SynapseAI 1.19.0
  examples/multi-node-training/EFA/Dockerfile
Labels: run-test
