Repository huggingface/optimum-habana, pull requests merged in 2024-06, with the labels that each got.

#973 Speculative sampling on Gaudi using Optimum-Habana
  examples/text-generation/README.md
  examples/text-generation/run_generation.py
  examples/text-generation/utils.py
  optimum/habana/transformers/generation/__init__.py
  optimum/habana/transformers/generation/candidate_generator.py
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
Labels: run-test

#1034 fix eos problem
  optimum/habana/transformers/generation/stopping_criteria.py
  optimum/habana/transformers/generation/utils.py
Labels: run-test, synapse1.16

#1030 fix performance issue in mistral (#181)
  optimum/habana/transformers/models/mistral/modeling_mistral.py
Labels: run-test, synapse1.16

#1029 fp8 textgen ci structure update
  examples/text-generation/run_generation.py
  optimum/habana/transformers/models/mixtral/modeling_mixtral.py
  tests/baselines/bert_large_uncased_whole_word_masking.json
  tests/baselines/distilbert_base_uncased.json
  tests/baselines/roberta_large.json
  tests/test_text_generation_example.py
Labels: run-test, synapse1.16

#1040 Fix a return value issue casued by PR 973
  examples/text-generation/run_lm_eval.py
Labels: run-test, synapse1.16

#829 Optimized inference of Starcoder2 model
  README.md
  docs/source/index.mdx
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/starcoder2/__init__.py
  optimum/habana/transformers/models/starcoder2/modeling_starcoder2.py
  tests/test_text_generation_example.py
Labels: run-test, synapse1.16

#980 Readme Update for FSDP
  examples/language-modeling/README.md
  tests/test_fsdp_examples.py
Labels: run-test, synapse 1.16_dependency

#1023 Add unifier script and disk offload flag usages to README.
  examples/text-generation/README.md
Labels: run-test, synapse1.16

#951 Enable fp8 inference for Llava-hf 7B and 13B in 1.16 release
  examples/image-to-text/README.md
  examples/image-to-text/quantization_config/act_maxabs_hw_weights_pcs_maxabs_pow2_quant.json
  examples/image-to-text/quantization_config/maxabs_measure.json
  examples/image-to-text/quantization_config/maxabs_measure_include_outputs.json
  examples/image-to-text/quantization_config/maxabs_quant.json
  examples/image-to-text/quantization_config/unit_scale_quant.json
  examples/image-to-text/run_pipeline.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/clip/__init__.py
  optimum/habana/transformers/models/clip/modeling_clip.py
  tests/test_image_to_text_example.py
Labels: run-test, synapse 1.16_dependency, synapse1.16

#1026 sasarkar/fusedrope inp bf16
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: synapse1.16

#1028 sarkar/cache_optimization
  examples/text-generation/utils.py
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: synapse1.16

#909 Add mixtral for meta device load due to mixtral-8x22b model size
  examples/text-generation/README.md
  optimum/habana/checkpoint_utils.py
Labels: run-test, synapse 1.16_dependency

#1010 Update unifier script
  examples/text-generation/quantization_tools/unify_measurements.py
Labels: run-test, synapse 1.16_dependency

#1044 Update text-generation CI configuration for falcon and Mixtral
  tests/test_text_generation_example.py
Labels: run-test, synapse 1.16_dependency

#972 Fast softmax
  examples/text-generation/quantization_config/act_maxabs_pow2_weights_pcs_opt_pow2_quant.json
  examples/text-generation/run_generation.py
  examples/text-generation/run_lm_eval.py
  examples/text-generation/utils.py
  optimum/habana/transformers/generation/configuration_utils.py
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: synapse 1.16_dependency

#974 Falcon optimization
  README.md
  examples/text-generation/README.md
  optimum/habana/transformers/models/falcon/modeling_falcon.py
Labels: run-test, synapse 1.16_dependency, synapse1.16

#976 Quantization for FSDPA
  examples/text-generation/README.md
Labels: synapse 1.16_dependency

#990 BERT training migrated to torch.compile (#203)
  examples/question-answering/README.md
  tests/test_examples.py
Labels: run-test, synapse 1.16_dependency

#1053 sarkar/Update test_examples.py
  tests/test_examples.py
Labels: synapse1.16

#1054 sarkar/Update modeling_llama.py: deepspeed fix for codellama
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: synapse1.16

#1050 No shapes in profilings by default (#233)
  examples/text-generation/run_generation.py
  examples/text-generation/text-generation-pipeline/pipeline.py
  optimum/habana/transformers/generation/utils.py
  optimum/habana/utils.py
Labels: synapse1.16

#1091 Fix 1st token latency time
  optimum/habana/transformers/generation/utils.py
Labels: run-test

#1095 Fix starcoder2 accuracy issue and optimize performance with fused rope
  optimum/habana/transformers/models/starcoder2/modeling_starcoder2.py
Labels: run-test
