Repository huggingface/optimum-habana, pull requests merged in 2024-09, with the labels that each got.

#1279 fix bug when running `google/paligemma-3b-mix-224`
  optimum/habana/transformers/models/gemma/modeling_gemma.py
Labels: review wip

#1196 Image to Image Generation Enabling
  examples/stable-diffusion/image_to_image_generation.py
  optimum/habana/diffusers/__init__.py
  optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py
  optimum/habana/diffusers/schedulers/scheduling_ddim.py
  tests/test_diffusers.py
Labels: review wip

#1277 Ig/Diffusers timing
  optimum/habana/diffusers/pipelines/controlnet/pipeline_controlnet.py
  optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
  optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_image_variation.py
  optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py
  optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py
  optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_ldm3d.py
  optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py
  optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
  optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py
  optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py
  optimum/habana/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py
  tests/test_diffusers.py
Labels: run-test

#1253 fix eos issue in finetune/generation
  examples/language-modeling/README.md
  examples/language-modeling/run_lora_clm.py
Labels: run-test

#1161 Falcon inference crash fix for falcon-40b model
  optimum/habana/transformers/models/falcon/modeling_falcon.py
Labels: run-test

#1284 Boost SDXL speed with initialized schedule step reset
  optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
  optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py
  optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py
Labels: run-test

#1325 Enable INC for llava models and change softmax to use torch.nn.functional.softmax as its supported module by INC
  examples/image-to-text/README.md
  examples/image-to-text/run_pipeline.py
  optimum/habana/transformers/models/clip/modeling_clip.py
Labels: run-test

#1292 add `--use_kv_cache` to image-to-text pipeline
  examples/image-to-text/README.md
  examples/image-to-text/run_pipeline.py
Labels: run-test

#1245 Trl upgrade
  examples/trl/dpo.py
  examples/trl/requirements.txt
  examples/trl/sft.py
  optimum/habana/trl/__init__.py
  optimum/habana/trl/trainer/__init__.py
  optimum/habana/trl/trainer/dpo_config.py
  optimum/habana/trl/trainer/dpo_trainer.py
  optimum/habana/trl/trainer/ppo_config.py
  optimum/habana/trl/trainer/ppo_trainer.py
  optimum/habana/trl/trainer/sft_config.py
  optimum/habana/trl/trainer/sft_trainer.py
Labels: run-test

#1333 use eager attention for wav2vec2
  optimum/habana/transformers/models/modeling_all_models.py
Labels: run-test

#1233 Add _reorder_cache back to Llama for HPU
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test

#1256 Improve MPT fp8
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/mpt/__init__.py
  optimum/habana/transformers/models/mpt/modeling_mpt.py
Labels: run-test

#1296 Ig/sdxl-ci-script-throughput
  tests/test_diffusers.py
Labels: run-test

#1338 add image so that transformers tests can run
  tests/resource/img/000000039769.png
  tests/transformers/tests/models/bridgetower/test_modeling_bridgetower.py
  tests/transformers/tests/models/swin/test_modeling_swin.py
  tests/transformers/tests/models/vit/test_modeling_vit.py
  tests/transformers/tests/utils/test_image_utils.py
Labels: run-test

#1344 Fixes the no attribute error with the falcon multicard test
  examples/language-modeling/run_lora_clm.py
Labels: run-test

#1339 Add profiler to sdxl mlperf pipeline
  optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_mlperf.py
Labels: run-test

#948 Fix decoder only generation
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/models/blip/modeling_blip_text.py
  optimum/habana/transformers/models/bloom/modeling_bloom.py
  optimum/habana/transformers/models/codegen/modeling_codegen.py
  optimum/habana/transformers/models/decilm/modeling_decilm.py
  optimum/habana/transformers/models/falcon/modeling_falcon.py
  optimum/habana/transformers/models/gemma/modeling_gemma.py
  optimum/habana/transformers/models/gpt2/modeling_gpt2.py
  optimum/habana/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py
  optimum/habana/transformers/models/gpt_neox/modeling_gpt_neox.py
  optimum/habana/transformers/models/gptj/modeling_gptj.py
  optimum/habana/transformers/models/llama/modeling_llama.py
  optimum/habana/transformers/models/mamba/modeling_mamba.py
  optimum/habana/transformers/models/mistral/modeling_mistral.py
  optimum/habana/transformers/models/mixtral/modeling_mixtral.py
  optimum/habana/transformers/models/mpt/modeling_mpt.py
  optimum/habana/transformers/models/opt/modeling_opt.py
  optimum/habana/transformers/models/persimmon/modeling_persimmon.py
  optimum/habana/transformers/models/phi/modeling_phi.py
  optimum/habana/transformers/models/qwen2/modeling_qwen2.py
  optimum/habana/transformers/models/stablelm/modeling_stablelm.py
  optimum/habana/transformers/models/starcoder2/modeling_starcoder2.py
  optimum/habana/transformers/models/t5/modeling_t5.py
  tests/transformers/tests/generation/test_utils.py
Labels: run-test

#1347 Upgrade gradient chekpointing
  optimum/habana/transformers/gradient_checkpointing.py
  optimum/habana/transformers/trainer.py
Labels: run-test

#1275 Add Whisper static generation
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/whisper/__init__.py
  optimum/habana/transformers/models/whisper/modeling_whisper.py
Labels: run-test

#1328 Fix deepseeed crash with Sentence Transformer Trainer
  examples/sentence-transformers-training/nli/README.md
  examples/sentence-transformers-training/nli/ds_config.json
  examples/sentence-transformers-training/nli/training_nli.py
  examples/sentence-transformers-training/sts/README.md
  examples/sentence-transformers-training/sts/ds_config.json
  examples/sentence-transformers-training/sts/training_stsbenchmark.py
  optimum/habana/sentence_transformers/__init__.py
  optimum/habana/sentence_transformers/modeling_utils.py
  optimum/habana/sentence_transformers/st_gaudi_trainer.py
  optimum/habana/sentence_transformers/st_gaudi_transformer.py
  tests/sentence_transformers/test_training_nli.py
  tests/sentence_transformers/test_training_stsbenchmark.py
Labels: run-test

#1330 fea(ci): reduced slow test_diffusers timing. minor fixes
  tests/test_diffusers.py
Labels: run-test

#1276 Transformer models generation supports user-provided input embeddings
  examples/text-generation/run_generation.py
  optimum/habana/transformers/generation/utils.py
Labels: run-test

#1294 vera/ln_tuning add and test case add
  examples/language-modeling/README.md
  examples/language-modeling/run_lora_clm.py
  tests/baselines/llama_7b.json
  tests/test_examples.py
Labels: run-test

#1350 recommend jemalloc for gpt-neox-20b 8x
  examples/language-modeling/README.md
Labels: synapse 1.18 dependency

#1282 gpt_big_code: make flash attention impl quantization friendly
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/gpt_bigcode/__init__.py
  optimum/habana/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py
Labels: run-test

#1319 Optimized inference of GPT-NEO model on HPU
  README.md
  docs/source/index.mdx
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/gpt_neo/__init__.py
  optimum/habana/transformers/models/gpt_neo/modeling_gpt_neo.py
  tests/test_text_generation_example.py
Labels: run-test

#1302 fix OOM when inference with llama-3.1-70b
  optimum/habana/transformers/modeling_attn_mask_utils.py
Labels: run-test

#1376 gpt_bigcode: fixed wrong indentation
  optimum/habana/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py
Labels: run-test

#1244 Add the diffusers examples of inference Tech
  examples/stable-diffusion/README.md
  examples/stable-diffusion/requirements.txt
  examples/stable-diffusion/text_to_image_generation.py
  optimum/habana/diffusers/models/unet_2d_condition.py
  optimum/habana/diffusers/utils/torch_utils.py
Labels: run-test
