Repository huggingface/optimum-habana, pull requests merged in 2024-03, with the labels that each got.

#704 Support speech recognition with whisper models and seq2seq.
  examples/speech-recognition/README.md
  examples/speech-recognition/run_speech_recognition_seq2seq.py
  tests/baselines/whisper_small.json
  tests/test_examples.py
  tests/utils.py
Labels: run-test

#715 Fix throughput calculation for diffusion models
  optimum/habana/diffusers/pipelines/controlnet/pipeline_controlnet.py
  optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
  optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_ldm3d.py
  optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py
  optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
Labels: run-test

#756 Update Mixtral-8x7B fp8 hqt example
  examples/text-generation/README.md
Labels: run-test

#650 Controlnet training
  Makefile
  examples/stable-diffusion/training/README.md
  examples/stable-diffusion/training/train_controlnet.py
  optimum/habana/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py
  tests/clip_coco_utils.py
  tests/test_diffusers.py
  tests/test_examples.py
Labels: run-test

#771 Override sdpa option in Gaudi
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/modeling_all_models.py
Labels: run-test, synapse 1.15

#752 Fix Llama-70B-FSDP model loading issue
  examples/language-modeling/run_lora_clm.py
  optimum/habana/transformers/training_args.py
Labels: run-test, synapse 1.15

#751 Expose Llama Fused OPs control from run_lora_clm.py
  examples/language-modeling/run_lora_clm.py
  optimum/habana/transformers/generation/configuration_utils.py
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/models/llama/modeling_llama.py
  optimum/habana/transformers/trainer.py
Labels: run-test, synapse 1.15

#778 Fixing tests by making static_shapes False
  optimum/habana/transformers/generation/utils.py
  tests/transformers/tests/generation/test_utils.py
Labels: run-test

#781 Further fixes for performance with internal bucketing.
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test

#791 Update summarization example README
  examples/summarization/README.md
Labels: run-test

#793 Block torchscript pytest because of seg fault issue
  tests/transformers/tests/test_modeling_common.py
Labels: run-test, synapse 1.15

#795 move img_mask@get_attn_mask() to hpu
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/swin/__init__.py
  optimum/habana/transformers/models/swin/modeling_swin.py
Labels: run-test, synapse 1.15

#796 Replacing obsolete API for mediapipe
  examples/contrastive-image-text/clip_media_pipe.py
Labels: run-test, synapse 1.15

#797 Fix redundant bucket internal and hpu graph setting
  optimum/habana/transformers/generation/utils.py
Labels: run-test

#732 enable phi series models.
  README.md
  docs/source/index.mdx
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/phi/__init__.py
  optimum/habana/transformers/models/phi/modeling_phi.py
  tests/test_text_generation_example.py
Labels: run-test

#806 Fix graph breaks in torch compile mode
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/models/llama/modeling_llama.py
  optimum/habana/transformers/trainer.py
Labels: run-test, synapse 1.15

#812 Fix FSDP in transformer4.38
  optimum/habana/transformers/trainer.py
Labels: run-test, synapse 1.15

#761 Add Llama test for fsdp
  .github/workflows/slow_tests_gaudi2.yml
  Makefile
  examples/language-modeling/README.md
  tests/test_fsdp_examples.py
Labels: run-test, synapse 1.15

#803 enable dynamic shapes for esmfold
  examples/protein-folding/run_esmfold.py
Labels: synapse 1.15

#745 Add Llama/Llama2 support in Question-Answering
  examples/question-answering/README.md
  examples/question-answering/run_qa.py
Labels: run-test, synapse 1.15

#804 Sarkar/mistral optimizations
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/mistral/__init__.py
  optimum/habana/transformers/models/mistral/modeling_mistral.py
Labels: run-test, synapse 1.15

#827 Revert Wav2Vec2 TDNNLayer forward function same as transformer v4.37.2
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/wav2vec2/__init__.py
  optimum/habana/transformers/models/wav2vec2/modeling_wav2vec2.py
Labels: run-test, synapse 1.15

#765 Rename whitelist & blacklist #71
  examples/text-generation/quantization_config/act_maxabs_hw_weights_pcs_maxabs_pow2_quant.json
  examples/text-generation/quantization_config/maxabs_measure.json
  examples/text-generation/quantization_config/maxabs_quant.json
  examples/text-generation/quantization_config/unit_scale_quant.json
Labels: run-test, synapse 1.15

#821 RMS Norm Graph break fix torch compile
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test, synapse 1.15

#817 add quantization config example including measure of output tensors
  examples/text-generation/quantization_config/maxabs_measure_include_outputs.json
Labels: synapse 1.15

#780 Enable Llama2 70B to run with hqt on single card (#50)
  examples/text-generation/run_generation.py
  examples/text-generation/run_lm_eval.py
  examples/text-generation/utils.py
Labels: run-test, synapse 1.15

#800 Added hqt unify_measurement script for synapse1.15
  examples/text-generation/quantization_tools/unify_measurements.py
Labels: run-test, synapse 1.15

#766 llama fp8 - enable non reuse cache flow for fp8 (#64)
  examples/text-generation/README.md
  examples/text-generation/run_generation.py
  examples/text-generation/run_lm_eval.py
  examples/text-generation/utils.py
  optimum/habana/transformers/generation/configuration_utils.py
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test, synapse 1.15

#693 add support for TinyLlama model
  optimum/habana/checkpoint_utils.py
Labels: run-test, synapse 1.15

#748 Clean-up BERT-BASE FSDP test
  tests/test_fsdp_examples.py
Labels: run-test, synapse 1.15

#787 Sarkar/mediapipe sdxl
  examples/stable-diffusion/requirements.txt
  examples/stable-diffusion/training/README.md
  examples/stable-diffusion/training/media_pipe_imgdir.py
  examples/stable-diffusion/training/requirements.txt
  examples/stable-diffusion/training/train_text_to_image_sdxl.py
  tests/test_diffusers.py
Labels: run-test, synapse 1.15

#832 Update README for FSDP
  examples/language-modeling/README.md
Labels: run-test, synapse 1.15

#818 Add Llama7b FSDP test for torch.compile mode
  tests/baselines/llama_7b.json
  tests/test_examples.py
Labels: run-test, synapse 1.15

#777 Enable Falcon FP8 inference
  examples/text-generation/README.md
  examples/text-generation/run_lm_eval.py
  examples/text-generation/utils.py
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/falcon/__init__.py
  optimum/habana/transformers/models/falcon/modeling_falcon.py
  tests/test_text_generation_example.py
Labels: run-test, synapse 1.15

#779 Enable hpu_graph support for wav2vec2-asr + custom ctc_loss only for Gaudi2
  examples/speech-recognition/README.md
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/wav2vec2/__init__.py
  optimum/habana/transformers/models/wav2vec2/modeling_wav2vec2.py
  tests/baselines/wav2vec2_large_lv60.json
Labels: run-test, synapse 1.15
