Repository huggingface/optimum-habana, pull requests merged in 2025-07, with the labels that each got.

#2075 text-generation requirements fix for transformers upgrade 4.51
  examples/text-generation/requirements_awq.txt
Labels: synapse 1.21

#2085 Enable dynamic quantization
  examples/text-generation/quantization_config/maxabs_quant_dynamic_quantization.json
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test, synapse 1.21

#2089 Use `PT_ENABLE_INT64_SUPPORT=1` for trl examples
  examples/trl/README.md
Labels: synapse 1.21

#2093 Add groups to slow_tests_image_to_text_example v1.18
  Makefile
  tests/test_image_to_text_example.py
Labels: synapse 1.21

#1948 Add qwen3 family
  README.md
  docs/source/index.mdx
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/qwen3/__init__.py
  optimum/habana/transformers/models/qwen3/modeling_qwen3.py
  optimum/habana/transformers/models/qwen3_moe/__init__.py
  optimum/habana/transformers/models/qwen3_moe/modeling_qwen3_moe.py
  tests/baselines/fixture/tests/test_text_generation_example.json
  tests/test_text_generation_example.py
Labels: synapse 1.21

#2099 Upgrade datasets to fix utf-8 encoding problem
  examples/audio-classification/requirements.txt
  examples/text-generation/requirements.txt
  examples/text-generation/requirements_lm_eval.txt
Labels: synapse 1.21

#1976 Llama 3.2 - Fix the issue for eager mode (#260)
  optimum/habana/transformers/models/mllama/modeling_mllama.py
Labels: run-test

#2122 Unnecessary changes
  Makefile
  examples/speech-recognition/README.md
  optimum/habana/accelerate/accelerator.py
  optimum/habana/transformers/models/gemma2/modeling_gemma2.py
  optimum/habana/transformers/models/mixtral/modeling_mixtral.py
  optimum/habana/transformers/models/qwen2_vl/modeling_qwen2_vl.py
  optimum/habana/utils.py
Labels: synapse1.22

#2121 Remove `requirements.txt` file
  requirements.txt
Labels: synapse1.22

#2119 Unify SetTrueOrFalseOrNone and StoreTrueFalseAction
  examples/text-generation/run_generation.py
Labels: synapse1.22

#2127 Remove old 1TL measuring
  examples/text-generation/run_generation.py
  optimum/habana/transformers/generation/utils.py
Labels: synapse1.22

#2040 Revert "Extra Content: text-generation experimental dir"
  examples/text-generation/experimental/run_generation.py
  examples/text-generation/experimental/run_lm_eval.py
  examples/text-generation/experimental/utils.py
Labels: synapse1.22

#1926 Add feature manager
  examples/trl/ppo.py
  optimum/habana/transformers/models/llama/modeling_llama.py
  optimum/habana/utils/environment.py
  optimum/habana/utils/feature_detection_utils.py
  optimum/habana/utils/features.py
  tests/test_features.py
Labels: run-test, synapse1.22

#1295 add boft support in stable-diffusion
  Makefile
  examples/stable-diffusion/text_to_image_generation.py
  examples/stable-diffusion/training/README.md
  examples/stable-diffusion/training/requirements.txt
  examples/stable-diffusion/training/train_dreambooth.py
  examples/stable-diffusion/training/train_dreambooth_lora_sdxl.py
  optimum/habana/peft/__init__.py
  optimum/habana/peft/layer.py
  tests/test_diffusers.py
Labels: run-test, synapse1.22

#2125 Fix Mllama model placement
  examples/image-to-text/run_pipeline.py
Labels: synapse1.22

#2146 Pin opencv version to 4.10.0.84 to W/A incompatibility with newer numpy.
  examples/stable-diffusion/requirements.txt
Labels: synapse 1.21
