Repository huggingface/optimum-habana, pull requests merged in 2025-04, with the labels that each got.

#1902 Llama2 70 b OOM fix
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test, transformers_4_49

#1905 Fix the flant5-xl training issue
  optimum/habana/transformers/models/t5/modeling_t5.py
Labels: transformers_future

#1906 Improve diffusers training download script
  examples/stable-diffusion/training/README.md
  examples/stable-diffusion/training/download_train_datasets.py
Labels: run-test, transformers_future

#1910 Update FP8 diffusers doc
  examples/stable-diffusion/README.md
Labels: run-test, transformers_future

#1909 Move model to device before wrapping with fsdp
  examples/question-answering/run_qa.py
Labels: run-test, transformers_future

#1857 Fix MPT regression
  optimum/habana/transformers/models/mpt/modeling_mpt.py
Labels: run-test, synapse 1.21

#1859 Optimize memory utilization by keeping logits in BF16.
  examples/image-to-text/run_pipeline.py
  optimum/habana/transformers/generation/configuration_utils.py
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/models/mllama/modeling_mllama.py
Labels: synapse 1.21

#1885 fix lost modules in regional compilation
  optimum/habana/accelerate/accelerator.py
Labels: synapse 1.21

#1860 Integrate DistributedAttention for Qwen2
  optimum/habana/transformers/models/qwen2/modeling_qwen2.py
Labels: synapse 1.21

#1892 [Llama-vision] Add support for Fused RMS Norm (#161)
  optimum/habana/transformers/models/mllama/modeling_mllama.py
Labels: run-test, synapse 1.21

#1911 [DeepSeek-V3] README update (#207)
  examples/text-generation/README.md
Labels: run-test, synapse 1.21

#1916 Skipping falcon rope scaling test (#221)
  tests/transformers/tests/models/falcon/test_modeling_falcon.py
Labels: run-test, synapse 1.21

#1932 Workaround for DS issue in Llama
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: synapse 1.21

#1901 Upgrade LM Eval to 0.4.7
  examples/text-generation/requirements_lm_eval.txt
  examples/text-generation/run_lm_eval.py
Labels: run-test, synapse 1.21

#1873 Enable torch compile for llama 3.2 vision
  examples/image-to-text/run_pipeline.py
Labels: run-test, synapse 1.21

#1880 Flag to enable leaf promotion to avoid graph breaks in ML…
  examples/language-modeling/run_lora_clm.py
  optimum/habana/transformers/training_args.py
Labels: run-test, synapse 1.21

#1881 Adding Deepspeed config for Llama3 Fine Tuning (#165)
  examples/language-modeling/llama3_ds_zero3_4k.json
Labels: run-test, synapse 1.21

#1923 Limit max pos embeds to 8k to prevent OOM (#227)
  examples/text-generation/utils.py
Labels: synapse 1.21

#1874 Fix prompt argument handling in `run_pipeline.py`
  examples/image-to-text/run_pipeline.py
Labels: run-test, synapse 1.21

#1924 Allow offline mode in CI tests (#232)
  tests/test_diffusers.py
Labels: run-test, synapse 1.21

#1933 Add trim_logits support in deepseekV3 (#180)
  optimum/habana/transformers/models/deepseek_v3/modeling_deepseek_v3.py
Labels: synapse 1.21

#1858 Adding memory and graph stats (#156)
  examples/image-to-text/run_pipeline.py
Labels: synapse 1.21

#1918 [SW-221482] Enable QLoRA tests with torch.compile mode
  tests/test_bnb_inference.py
  tests/test_bnb_qlora.py
Labels: run-test, synapse 1.21

#1899 detr: fix possible incorrect tensor type
  optimum/habana/transformers/models/detr/modeling_detr.py
Labels: run-test

#1785 Add flag to enable compiled_autograd with Deepspeed for training (#147)
  optimum/habana/accelerate/accelerator.py
  optimum/habana/transformers/trainer.py
  optimum/habana/transformers/training_args.py
Labels: synapse 1.21

#1920 Reimplement HabanaGenerationTime
  examples/image-classification/run_timm_example.py
  examples/image-to-text/run_pipeline.py
  examples/object-detection/run_example.py
  examples/object-segmentation/run_example.py
  examples/object-segmentation/run_example_sam.py
  examples/protein-folding/run_esmfold.py
  examples/pytorch-image-models/inference.py
  examples/stable-diffusion/training/textual_inversion.py
  examples/stable-diffusion/training/textual_inversion_sdxl.py
  examples/stable-diffusion/training/train_controlnet.py
  examples/stable-diffusion/training/train_text_to_image_sdxl.py
  examples/text-feature-extraction/run_feature_extraction.py
  examples/text-generation/run_generation.py
  examples/text-generation/run_lm_eval.py
  examples/text-generation/text-generation-pipeline/run_pipeline.py
  examples/text-generation/text-generation-pipeline/run_pipeline_langchain.py
  examples/text-generation/utils.py
  examples/text-to-speech/run_pipeline.py
  examples/trl/ppo.py
  examples/video-classification/run_example.py
  examples/visual-question-answering/run_openclip_vqa.py
  examples/visual-question-answering/run_pipeline.py
  examples/zero-shot-object-detection/run_example.py
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/trainer.py
  optimum/habana/trl/trainer/ppo_trainer.py
  optimum/habana/utils.py
  tests/test_feature_extraction.py
  tests/test_image_classification.py
  tests/test_image_segmentation.py
  tests/test_object_detection.py
  tests/test_object_segmentation.py
  tests/test_sentence_transformers.py
  tests/test_table_transformer.py
  tests/test_video_mae.py
  tests/test_zero_shot_object_detection.py
Labels: synapse 1.21

#1941 Pad the examples for QLoRa finetuning test
  setup.py
  tests/baselines/fixture/tests/test_bnb_inference.json
  tests/baselines/fixture/tests/test_bnb_qlora.json
  tests/test_bnb_inference.py
  tests/test_bnb_qlora.py
Labels: run-test, synapse 1.21

#1894 [Llama-Vision] Trim logits (#162)
  examples/image-to-text/run_pipeline.py
  optimum/habana/transformers/models/mllama/modeling_mllama.py
Labels: synapse 1.21

#1946 Move bitsandbytes requirements from setup.py to bnb tests
  setup.py
  tests/test_bnb_inference.py
  tests/test_bnb_qlora.py
Labels: synapse 1.21

#1887 Support allow_unspec_int_on_nn_module
  optimum/habana/transformers/training_args.py
Labels: run-test, synapse 1.21

#1917 Align cross_attention_mask for Llama 3.2 90B to avoid partial writes and graph retracing
  optimum/habana/transformers/models/mllama/modeling_mllama.py
Labels: run-test, synapse 1.21

#1903 Tokenizer config fix for dynamic mode (#144)
  examples/text-generation/run_generation.py
Labels: run-test, synapse 1.21

#1886 Support compile from the 2nd iteration
  optimum/habana/transformers/trainer.py
  optimum/habana/transformers/training_args.py
Labels: run-test, synapse 1.21

#1600 add cogvideox support for gaudi.
  examples/stable-diffusion/README.md
  examples/stable-diffusion/text_to_video_generation.py
  optimum/habana/diffusers/__init__.py
  optimum/habana/diffusers/models/attention_processor.py
  optimum/habana/diffusers/models/autoencoders/autoencoder_kl_cogvideox.py
  optimum/habana/diffusers/models/cogvideox_transformer_3d.py
  optimum/habana/diffusers/models/embeddings.py
  optimum/habana/diffusers/pipelines/cogvideox/pipeline_cogvideox.py
  tests/test_diffusers.py
Labels: run-test, synapse 1.21

#1897 Add FSDP config for Granite model
  examples/language-modeling/granite_fsdp_config.json
  tests/baselines/fixture/tests/test_fsdp_examples.json
  tests/test_fsdp_examples.py
Labels: run-test, synapse 1.21

#1940 fea(): ReadMe remote_trust fixes
  examples/speech-recognition/README.md
  examples/text-generation/README.md
Labels: run-test

#1868 Add Moonlight Support
  Makefile
  README.md
  docs/source/index.mdx
  examples/text-generation/README.md
  examples/text-generation/requirements_lm_eval.txt
  examples/text-generation/run_generation.py
  examples/text-generation/utils.py
  tests/baselines/fixture/tests/test_text_generation_example.json
  tests/test_text_generation_example.py
Labels: synapse 1.21

#1668 Add GLM4V
  README.md
  docs/source/index.mdx
  examples/image-to-text/README.md
  examples/image-to-text/requirements.txt
  examples/image-to-text/run_pipeline.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/glm4v/__init__.py
  optimum/habana/transformers/models/glm4v/configuration_chatglm.py
  optimum/habana/transformers/models/glm4v/modeling_chatglm.py
  optimum/habana/transformers/models/glm4v/tokenization_chatglm.py
  optimum/habana/transformers/models/glm4v/visual.py
  tests/baselines/fixture/tests/test_image_to_text_example.json
  tests/test_image_to_text_example.py
Labels: run-test
