Repository huggingface/optimum-habana, pull requests merged in 2025-05, with the labels that each got.

#1914 Use data cache in slow_tests_8x (#214)
  Makefile
  tests/test_examples.py
Labels: run-test, synapse 1.21

#1908 Add support for expert parallelism with mixtral
  examples/text-generation/utils.py
  optimum/habana/transformers/models/mixtral/modeling_mixtral.py
  tests/baselines/fixture/tests/test_text_generation_example.json
Labels: run-test, synapse 1.21

#1968 Update t5-small samples_per_second value
  tests/baselines/fixture/tests/test_encoder_decoder.json
Labels: synapse 1.21

#1971 Ig/pytest t5 robetra fix
  tests/transformers/tests/models/roberta/test_modeling_roberta.py
  tests/transformers/tests/models/t5/test_modeling_t5.py
Labels: synapse 1.21

#1969 adjust VideoLlavaProcessor to avoid performance regression on gaudi3
  examples/video-comprehension/run_example.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/video_llava/__init__.py
  optimum/habana/transformers/models/video_llava/processing_video_llava.py
  tests/baselines/fixture/tests/test_video_llava.json
Labels: synapse 1.21

#1925 Update makefile for explicit lazy mode
  Makefile
Labels: run-test, synapse 1.21

#1927 [SW-216003] Enable regional compilation in text generation
  examples/text-generation/run_generation.py
  examples/text-generation/utils.py
Labels: run-test, synapse 1.21

#1947 README changes for Llama3.1 8B Finetuning with LoRA
  examples/language-modeling/README.md
  tests/baselines/fixture/tests/test_fp8_examples.json
  tests/test_fp8_examples.py
Labels: run-test, synapse 1.21

#1875 pt2e quant changes into the main script (#191)
  examples/text-generation/quantization_tools/pt2e.py
  examples/text-generation/run_generation.py
  examples/text-generation/run_lm_eval.py
  examples/text-generation/utils.py
Labels: run-test, synapse 1.21

#1982 Switch to Spawn in PyTorch DataLoader when num_worker>0
  optimum/habana/accelerate/accelerator.py
Labels: run-test, synapse 1.21

#1990 Add additional info about attn batch split flag
  examples/text-generation/README.md
Labels: run-test
