Repository huggingface/optimum-habana, pull requests merged in 2025-02, with the labels that each got.

#1681 Added quant config files for new scenarios
  examples/text-generation/quantization_config/pow2_quant.json
  examples/text-generation/quantization_config/weight_opt_quant.json
Labels: run-test

#1726 Removing HL_DS_DISTRIBUTED_ATTENTION_SEQ_DIM as it's not needed from 1.20
  examples/language-modeling/README.md
Labels: run-test, synapse1.20

#1730 Update DS config to align with recommended settings
  examples/language-modeling/llama3_ds_zero1_config.json
Labels: run-test, synapse1.20

#1619 Add dynamo cache size limit option
  optimum/habana/transformers/training_args.py
Labels: run-test

#1705 Fix graph breaks in Mixtral (#65)
  optimum/habana/transformers/models/mixtral/modeling_mixtral.py
Labels: run-test, synapse1.20

#1740 Resolve 'NoneType' object has no attribute 'gate_proj' err when applying EP in DeepSeek-V2
  optimum/habana/transformers/models/deepseek_v2/modeling_deepseek_v2.py
Labels: run-test

#1739 edit mixtral quantization config file (#114)
  examples/text-generation/quantization_config/maxabs_quant_mixtral.json
Labels: run-test

#1737 Fix the incorrect output of sdxl inpaint
  optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py
  optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py
  optimum/habana/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py
  tests/test_diffusers.py
Labels: run-test

#1714 Supports Bitsandbytes development on HPU (#117)
  optimum/habana/accelerate/utils/modeling.py
  optimum/habana/quantizers/bitsandbytes.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/llama/modeling_llama.py
  tests/test_bnb_inference.py
  tests/test_bnb_qlora.py
Labels: run-test

#1522 add video-llava model support
  Makefile
  README.md
  docs/source/index.mdx
  examples/video-comprehension/README.md
  examples/video-comprehension/requirements.txt
  examples/video-comprehension/run_example.py
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/llama/modeling_llama.py
  optimum/habana/transformers/models/video_llava/__init__.py
  optimum/habana/transformers/models/video_llava/modeling_video_llava.py
  tests/test_video_llava.py
Labels: run-test

#1725 Add batch dim idx to support latest deepspeed DistributedAttention
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test, synapse1.20

#1617 Add the inline_inbuilt_nn_modules option
  optimum/habana/transformers/training_args.py
Labels: run-test

#1709 Clean up README examples
  examples/contrastive-image-text/README.md
  examples/language-modeling/README.md
  examples/question-answering/README.md
  examples/summarization/README.md
Labels: run-test

#1640 Add batch splitting in attention layer to hide NIC latency(#14)
  examples/text-generation/README.md
  examples/text-generation/run_generation.py
  examples/text-generation/utils.py
  optimum/habana/transformers/generation/configuration_utils.py
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test

#1746 Accuracy fix for llama3.1-70B in eager/torch.compile mode
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test

#1748 Adjust baselines for lower number of epochs improved perplexity, lowe…
  tests/baselines/falcon_40b.json
Labels: run-test

#1749 Change clip-roberta/bridgetower not to use fast_ddp
  examples/contrastive-image-text/README.md
  tests/baselines/bridgetower_large_itm_mlm_itc.json
  tests/baselines/clip_roberta.json
  tests/test_examples.py
Labels: run-test

#1756 fix llama FP8 perf issue, kvcache.update should be used since FP8 pat…
  optimum/habana/transformers/models/llama/modeling_llama.py
  tests/baselines/llama_7b.json
Labels: run-test

#1753 Adds requirements.txt to sentence transformers training paraphrases
  examples/sentence-transformers-training/paraphrases/README.md
  examples/sentence-transformers-training/paraphrases/requirements.txt
Labels: run-test

#1754 Add requirements.txt to sentence transformer training sts
  examples/sentence-transformers-training/sts/README.md
  examples/sentence-transformers-training/sts/requirements.txt
Labels: run-test

#1554 Add diffuser tests for optimized sdxl flow on HPU
  tests/test_diffusers.py
Labels: run-test

#1743 Add _prepare_inputs_for_generation
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
Labels: run-test, transformers_future

#1670 Enable the i2vgen pipeline
  README.md
  docs/source/index.mdx
  examples/stable-diffusion/README.md
  examples/stable-diffusion/image_to_video_generation.py
  optimum/habana/diffusers/__init__.py
  optimum/habana/diffusers/pipelines/i2vgen_xl/pipeline_i2vgen_xl.py
  tests/test_diffusers.py
Labels: run-test

#1732 Implement baselines as a fixture and with simple rebase support
  conftest.py
  tests/baselines/fixture/tests/test_encoder_decoder.json
  tests/baselines/fixture/tests/test_fp8_examples.json
  tests/baselines/fixture/tests/test_fsdp_examples.json
  tests/baselines/fixture/tests/test_image_to_text_example.json
  tests/baselines/fixture/tests/test_openclip_vqa.json
  tests/baselines/fixture/tests/test_pipeline.json
  tests/baselines/fixture/tests/test_sentence_transformers.json
  tests/baselines/fixture/tests/test_text_generation_example.json
  tests/test_encoder_decoder.py
  tests/test_fp8_examples.py
  tests/test_fsdp_examples.py
  tests/test_image_to_text_example.py
  tests/test_openclip_vqa.py
  tests/test_pipeline.py
  tests/test_sentence_transformers.py
  tests/test_text_generation_example.py
Labels: run-test, transformers_future

#1747 Fix the issue with --load_quantized_model_with_autoawq
  Makefile
  examples/text-generation/README.md
  examples/text-generation/requirements_awq.txt
  optimum/habana/transformers/integrations/awq.py
Labels: run-test, transformers_future

#1750 fix dpo crash in transformers 4.48
  optimum/habana/trl/trainer/dpo_trainer.py
Labels: run-test, transformers_future

#1751 fix the output length in image_to_text test to make sure the outpu…
  examples/image-to-text/run_pipeline.py
  tests/test_image_to_text_example.py
Labels: run-test

#1760 Fix for Falcon image-to-text crash
  examples/image-to-text/run_pipeline.py
Labels: run-test, transformers_future

#1755 Fix Experts Indexing in MoE for Mixtral: Align experts_max with Number of Available Experts
  optimum/habana/transformers/models/mixtral/modeling_mixtral.py
Labels: run-test

#1771 Fix llama attr
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test, transformers_future

#1767 Add requirements.txt to sentence transformers nli example
  examples/sentence-transformers-training/nli/README.md
  examples/sentence-transformers-training/nli/requirements.txt
Labels: run-test

#1764 UX code change
  examples/text-generation/utils.py
Labels: run-test

#1759 fix dependency issue with --load_quantized_model_with_autoawq
  Makefile
  examples/text-generation/README.md
  examples/text-generation/requirements_awq.txt
Labels: run-test

#1683 Enable saving and loading FP8 model
  examples/text-generation/README.md
  examples/text-generation/run_generation.py
  examples/text-generation/run_lm_eval.py
  examples/text-generation/utils.py
Labels: run-test

#1775 update llama scaling
  optimum/habana/transformers/models/llama/modeling_llama.py
Labels: run-test, transformers_future

#1761 Add HPU fp8 Dynamic MOE (#93)
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/mixtral/__init__.py
  optimum/habana/transformers/models/mixtral/modeling_mixtral.py
Labels: run-test

#1773 Update measurements for Stable Diffusion XL
  examples/stable-diffusion/quantization/stable-diffusion-xl/measure/fp8_hooks_maxabs.json
  examples/stable-diffusion/quantization/stable-diffusion-xl/measure/fp8_hooks_maxabs.npz
Labels: run-test

#1783 Enable wav2vec-large model for speech_recognition test
  tests/utils.py
Labels: run-test

#1779 Update multi-node-training environment variables for GaudiNIC
  examples/multi-node-training/GaudiNIC/.deepspeed_env
  examples/multi-node-training/README.md
Labels: run-test

#1781 Fixed Gemma2 error when saving pretrain
  optimum/habana/transformers/models/gemma2/modeling_gemma2.py
Labels: run-test

#1745 Enable Llama 3.1 405B in FP8 (#124)
  examples/text-generation/quantization_config/unit_scale_quant.json
  examples/text-generation/utils.py
Labels: run-test

#1487 support llava1.5 lora finetuning.
  examples/image-to-text/README.md
  examples/image-to-text/run_image2text_lora_finetune.py
  optimum/habana/transformers/models/llava/modeling_llava.py
  tests/baselines/llava_1_5_7b_hf.json
  tests/test_examples.py
  tests/utils.py
Labels: run-test

#1780 Simplify text-gen readme
  examples/text-generation/README.md
Labels: transformers_future

#1778 Create Habana_Validated_Models.md to list all the models validated
  README.md
  tests/Habana_Validated_Models.md
Labels: run-test

#1718 Diffusers: Simplified the README files. Updated CI tests.
  README.md
  examples/stable-diffusion/README.md
  examples/stable-diffusion/training/README.md
  tests/test_diffusers.py
Labels: transformers_future

#1735 DeepSeek_v3 support
  README.md
  docs/source/index.mdx
  examples/text-generation/README.md
  optimum/habana/transformers/generation/utils.py
  optimum/habana/transformers/modeling_utils.py
  optimum/habana/transformers/modeling_utils_transformers.py
  optimum/habana/transformers/models/__init__.py
  optimum/habana/transformers/models/deepseek_v3/__init__.py
  optimum/habana/transformers/models/deepseek_v3/configuration_deepseek_v3.py
  optimum/habana/transformers/models/deepseek_v3/modeling_deepseek_v3.py
Labels: run-test

#1757 Enable attention selection for wav2vec2
  examples/audio-classification/README.md
  examples/audio-classification/run_audio_classification.py
  examples/speech-recognition/README.md
  examples/speech-recognition/run_speech_recognition_ctc.py
  optimum/habana/transformers/models/wav2vec2/modeling_wav2vec2.py
  optimum/habana/transformers/training_args.py
Labels: run-test

#1788 Add --attn_implementation to wav2vec2 slow tests
  tests/test_examples.py
Labels: run-test

#1792 add sentencepiece to the requirements
  examples/text-to-speech/requirements.txt
Labels: run-test

#1799 Fix the restart issue for Sentence Transformer STS example in validation
  examples/sentence-transformers-training/nli/README.md
  examples/sentence-transformers-training/nli/training_nli.py
  examples/sentence-transformers-training/sts/README.md
  examples/sentence-transformers-training/sts/training_stsbenchmark.py
Labels: run-test

#1795 exp flags for acc issues
  examples/audio-classification/README.md
  examples/text-generation/README.md
Labels: run-test

#1787 Add device auto-discovery and cli option
  conftest.py
  tests/test_bnb_inference.py
  tests/test_bnb_qlora.py
  tests/test_custom_file_input.py
  tests/test_diffusers.py
  tests/test_encoder_decoder.py
  tests/test_examples.py
  tests/test_feature_extraction.py
  tests/test_fp8_examples.py
  tests/test_fsdp_examples.py
  tests/test_functional_text_generation_example.py
  tests/test_image_to_text_example.py
  tests/test_object_detection.py
  tests/test_openclip_vqa.py
  tests/test_sentence_transformers.py
  tests/test_table_transformer.py
  tests/test_text_generation_example.py
  tests/test_video_llava.py
  tests/test_video_mae.py
  tests/test_zero_shot_object_detection.py
  tests/utils.py
Labels: run-test

#1798 [1.20.0] Temporary workaround to avoid segmentation fault
  optimum/habana/transformers/models/mixtral/modeling_mixtral.py
Labels: run-test
